services:
  - type: web
    name: acro-monitor
    env: python
    buildCommand: pip install -r ping-service/requirements.txt
    startCommand: python monitor_acro_match.py
    workingDirectory: src
    autoDeploy: true
