services:
  - type: web
    name: acro_match
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: web
    name: match-form
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free

  - type: web
    name: acro-match-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor_service.py
    rootDir: ping-service/src
    plan: free

  - type: cron
    name: keep-alive-ping
    schedule: "*/5 * * * *"  # Every 5 min
    runtime: python
    buildCommand: ""
    startCommand: python src/keep_alive.py  